export default {
  PACKAGES_STORAGE_PATH: "/data/packages.json",
  LANGUAGES_STORAGE_PATH: "/data/languages.json",
  SETTINGS_STORAGE_PATH: "/data/settings.json",
  DEFAULT_NETWORK_NAME: "epi",
  DEFAULT_REFRESH_PERIOD: "3600",
  DEFAULT_SOCKET_CAMERA_FPS: "15",
  DEFAULT_HTTP_CAMERA_FPS: "15",
  XSL_PATH: "/code/assets/xml/leaflet.xsl",
  SN_LABEL: "Serial number",
  SN_FAIL_ICON: "assets/icons/serial_number/sn_fail_red_x.svg",
  SN_FAIL_MESSAGE: "Failed",
  SN_RECALLED_MESSAGE: "Recalled",
  BATCH_RECALLED_MESSAGE: "Batch Recalled",
  SN_DECOMMISSIONED_MESSAGE: "Decommissioned",
  SN_OK_ICON: "assets/icons/serial_number/sn_ok.png",
  SN_GRAY_ICON: "assets/icons/serial_number/SN_gray_icon.svg",
  SN_OK_MESSAGE: "Verified",
  SN_UNABLE_TO_VERIFY_MESSAGE: "Unable to verify",
  PRODUCT_STATUS_FAIL_ICON: "assets/icons/product_status/ps_fail_red_x.svg",
  PRODUCT_STATUS_FAIL_MESSAGE: "Incorrect expiry date on pack",
  PRODUCT_EXPIRED_MESSAGE: "Product expired",
  PRODUCT_STATUS_OK_ICON: "assets/icons/product_status/ps_ok.png",
  PRODUCT_STATUS_GRAY_ICON: "assets/icons/product_status/ps_gray_icon.svg",
  PRODUCT_STATUS_OK_MESSAGE: "Verified",
  PRODUCT_STATUS_UNABLE_TO_VALIDATE_MESSAGE: "Unable to validate",
  PACK_VERIFICATION_GRAY_ICON: "assets/icons/pack_verification/svg/PV_gray_icon.svg",
  PACK_VERIFICATION_ICON: "assets/icons/pack_verification/svg/PV_icon.svg",
  PACK_VERIFICATION_UNABLE_TO_VERIFY_MESSAGE: "Unable to verify",
  HISTORY_TABLE : "history_table",
  PATH_TO_PRODUCT_DSU: "/product/",
  PATH_TO_BATCH_DSU: "/batch/",
  HISTORY_ITEM_DEFAULT_ICON: "./assets/icons/product_image_placeholder.svg",
  IOS_USE_FRAMES: 'dev-options:ios-use-frames'
}
